#!/bin/bash
set -e

# 定义颜色输出
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=======================================================${NC}"
echo -e "${GREEN}    欢迎配置 5x49 影音管理系统！${NC}"
echo -e "${GREEN}    Welcome to 5x49 Media Server Setup${NC}"
echo -e "${GREEN}=======================================================${NC}"
echo ""
echo "此脚本将帮助您快速生成 .env 配置文件"
echo "This script will help you quickly generate the .env file"
echo ""

# 默认值
DEFAULT_MEDIA_DIR="/volume1/video/movies"

# 1. 媒体目录
read -r -p "请输入您的媒体文件夹路径 / Enter your media directory path (默认/Default: $DEFAULT_MEDIA_DIR): " MEDIA_DIR
MEDIA_DIR=${MEDIA_DIR:-$DEFAULT_MEDIA_DIR}

# 2. TMDB API Key
read -r -p "请输入您的 TMDB API Key / Enter your TMDB API Key (选填/Optional): " TMDB_API_KEY

# 3. OpenRouter API Key
read -r -p "请输入您的 OpenRouter API Key / Enter your OpenRouter API Key (选填/Optional): " OPENROUTER_API_KEY

# 检查是否存在现有的 .env 文件以防止误覆盖
if [ -f ".env" ]; then
    echo ""
    echo -e "${YELLOW}警告: 发现已存在的 .env 文件，已自动将其备份为 .env.backup${NC}"
    echo -e "${YELLOW}Warning: Existing .env file found, backed it up to .env.backup${NC}"
    cp .env .env.backup
fi

# 生成 .env 文件
cat <<EOF > .env
# Auto-generated by setup.sh
MEDIA_DIR=$MEDIA_DIR
TMDB_API_KEY=$TMDB_API_KEY
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
EOF

echo ""
echo -e "${GREEN}=======================================================${NC}"
echo -e "${GREEN}配置完成！已自动生成 .env 文件。${NC}"
echo -e "${GREEN}Setup complete! The .env file has been generated.${NC}"
echo -e "${GREEN}-------------------------------------------------------${NC}"
echo "您可以随时修改目录下的 .env 文件来更新配置。"
echo "You can edit the .env file in this directory anytime."
echo ""
echo "现在您可以使用以下命令启动服务："
echo "Now you can start the services using:"
echo -e "${GREEN}  docker-compose up -d${NC}"
echo -e "${GREEN}=======================================================${NC}"
